# Generated by Django 5.1.4 on 2025-01-04 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(help_text='Diretrizes que definem o comportamento e objetivo do assistente.', verbose_name='Instruções')),
                ('name', models.CharField(help_text='Identificação única do assistente (máximo de 15 caracteres).', max_length=15, unique=True, verbose_name='Nome')),
                ('model', models.CharField(choices=[('gpt-4o', 'gpt-4o'), ('gpt-4o-mini', 'gpt-4o-mini')], help_text='Escolha o tipo ou versão do modelo de IA a ser usado.', max_length=30, verbose_name='Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o assistente está ativo para uso.', verbose_name='Ativo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assistente',
                'verbose_name_plural': 'Assistentes',
                'db_table': 'chatbot_assistant',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('CASUAL', 'Casual'), ('FORMAL', 'Formal'), ('DIRETO AO PONTO', 'Direto ao Ponto'), ('AMIGAVEL', 'Amigável'), ('PROFISSIONAL', 'Profissional'), ('PERSUASIVO', 'Persuasivo'), ('INFORMATIVO', 'Informativo'), ('MOTIVADOR', 'Motivador'), ('NEUTRO', 'Neutro'), ('EMPATICO', 'Empático')], help_text='Exemplo: casual, formal, direto ao ponto, etc.', max_length=50, verbose_name='Tom de Comunicação')),
                ('vocabulary', models.TextField(help_text='Descreva o vocabulário e a abordagem que o agente deve usar.', verbose_name='Vocabulário e Abordagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o assistente está ativo para uso.', verbose_name='Ativo')),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='chatbot.assistant', verbose_name='Assistente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tom de Comunicação',
                'verbose_name_plural': 'Tons de Comunicação',
                'db_table': 'chatbot_communication',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escreva o nome da regra.', max_length=30, verbose_name='Regra')),
                ('description', models.TextField(help_text='Defina o papel principal e as responsabilidades do agente.', verbose_name='Descrição do Papel')),
                ('objective', models.TextField(help_text='Especifique o objetivo final do agente nesta interação.', verbose_name='Objetivo Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o assistente está ativo para uso.', verbose_name='Ativo')),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_for_user', to='chatbot.assistant', verbose_name='Assistente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Regra',
                'verbose_name_plural': 'Regras',
                'db_table': 'chatbot_role',
                'ordering': ['id'],
            },
        ),
    ]
