# Generated by Django 5.1.4 on 2025-01-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identificador único da sessão do usuário.', max_length=255, unique=True, verbose_name='ID da Sessão')),
                ('messages', models.JSONField(help_text='Armazena o histórico completo de mensagens em formato JSON.', verbose_name='Histórico de Mensagens')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data em que o histórico foi criado.', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização no histórico.', verbose_name='Última Atualização')),
                ('communication', models.ForeignKey(blank=True, help_text='Define o tom de comunicação usado nessa sessão.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.communication', verbose_name='Tom de Comunicação')),
            ],
            options={
                'verbose_name': 'Histórico de Conversa',
                'verbose_name_plural': 'Históricos de Conversa',
                'db_table': 'chatbot_chat_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
