# Generated by Django 5.1.4 on 2025-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='messages',
            field=models.JSONField(default=list, help_text='Armazena o histórico completo de mensagens em formato JSON.', verbose_name='Histórico de Mensagens'),
        ),
    ]
